import type { ProductType, SummaryKpiType, CategoryIndex, ContributionType } from "./types"

// Enhanced mock data for products with new features
export const products: ProductType[] = [
  {
    id: 1,
    name: "iPhone 16 Pro",
    priceArgentina: 1060,
    priceArgentinaCurreny: "USD",
    priceUSA: 1000,
    image: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-16-pro-lineup-select-202409?wid=940&hei=1112&fmt=jpeg&qlt=90&.v=1718554600260",
    lastUpdated: "2025-04-16",
    brand: "Apple",
    category: "tecnologia",
    dataSource: "scraped",
    categoryType: "tech",
    sourceUrl: "https://apple.com/iphone-16-pro",
    votes: { up: 24, down: 3, userVote: null },
  },
  {
    id: 2,
    name: "Nike Air Force 1",
    priceArgentina: 199999,
    priceArgentinaCurreny: "ARS",
    priceUSA: 115,
    image: "https://nikearprod.vtexassets.com/arquivos/ids/155413-1200-1200?width=1200&height=1200&aspect=true",
    lastUpdated: "2025-04-16",
    brand: "Nike",
    category: "ropa",
    dataSource: "scraped",
    categoryType: "fashion",
    sourceUrl: "https://nike.com/air-force-1",
    votes: { up: 18, down: 2, userVote: null },
  },
  {
    id: 3,
    name: "10 Cápsulas Café Nespresso Colombia",
    priceArgentina: 20500,
    priceArgentinaCurreny: "ARS",
    priceUSA: 9,
    image: "https://www.nespresso.com/ecom/medias/sys_master/public/16653527384094/colombia-2x.png?impolicy=small&imwidth=224&imdensity=1",
    lastUpdated: "2025-04-16",
    brand: "Nespresso",
    category: "gastronomia",
    dataSource: "manual",
    categoryType: "food",
    sourceUrl: "https://nespresso.com/colombia",
    votes: { up: 12, down: 1, userVote: null },
  },
  {
    id: 4,
    name: "Camiseta Aniversario Argentina",
    priceArgentina: 149999,
    priceArgentinaCurreny: "ARS",
    priceUSA: 100,
    image: "https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/cae76a03cc30414289c3c82a238ad6ed_9366/Camiseta_Aniversario_50_Anos_Seleccion_Argentina_Azul_JF0395_01_laydown.jpg",
    lastUpdated: "2025-04-16",
    brand: "Adidas",
    category: "ropa",
    dataSource: "scraped",
    categoryType: "fashion",
    sourceUrl: "https://adidas.com.ar/camiseta-argentina",
    votes: { up: 31, down: 4, userVote: null },
  },
  {
    id: 5,
    name: "MacBook Air M3",
    priceArgentina: 1899,
    priceArgentinaCurreny: "USD",
    priceUSA: 1299,
    image: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-select-20220606?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1653084303665",
    lastUpdated: "2025-04-15",
    brand: "Apple",
    category: "tecnologia",
    dataSource: "user_contributed",
    categoryType: "tech",
    sourceUrl: "https://mercadolibre.com.ar/macbook-air-m3",
    votes: { up: 8, down: 2, userVote: null },
    contributorName: "TechUser123",
    verificationStatus: "pending",
  },
  {
    id: 6,
    name: "Zapatillas Adidas Ultraboost",
    priceArgentina: 165000,
    priceArgentinaCurreny: "ARS", 
    priceUSA: 180,
    image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/fbaf991a78bc4896a3e9ad7800abcec6_9366/Zapatillas_Ultraboost_22_Negro_GZ0127_01_standard.jpg",
    lastUpdated: "2025-04-14",
    brand: "Adidas",
    category: "ropa",
    dataSource: "verified",
    categoryType: "fashion",
    sourceUrl: "https://adidas.com.ar/ultraboost",
    votes: { up: 15, down: 0, userVote: null },
    contributorName: "RunnerBA",
    verificationStatus: "approved",
  },
]

// Mock data for category indices
export const categoryIndices: CategoryIndex[] = [
  {
    category: "tech",
    name: "Tecnología",
    index: 65,
    trend: "up",
    color: "red",
    productCount: 2,
  },
  {
    category: "fashion",
    name: "Moda",
    index: -8,
    trend: "down", 
    color: "green",
    productCount: 3,
  },
  {
    category: "food",
    name: "Gastronomía",
    index: 12,
    trend: "stable",
    color: "yellow",
    productCount: 1,
  },
  {
    category: "home",
    name: "Hogar",
    index: 23,
    trend: "up",
    color: "yellow",
    productCount: 0,
  },
  {
    category: "cars",
    name: "Autos",
    index: 89,
    trend: "up", 
    color: "red",
    productCount: 0,
  },
]

// Mock data for pending contributions
export const mockContributions: ContributionType[] = [
  {
    id: 1,
    productName: "Samsung Galaxy S24",
    priceArgentina: 1200,
    priceArgentinaCurrency: "USD",
    priceUSA: 899,
    category: "tech",
    sourceUrl: "https://samsung.com.ar/galaxy-s24",
    contributorName: "TechReviewer",
    submittedAt: "2025-04-16T10:30:00Z",
    status: "pending",
    votes: { up: 5, down: 1 },
  },
  {
    id: 2,
    productName: "Coca Cola 2.25L",
    priceArgentina: 3500,
    priceArgentinaCurrency: "ARS",
    priceUSA: 2.5,
    category: "food",
    sourceUrl: "https://carrefour.com.ar/coca-cola",
    contributorName: "LocalShopper",
    submittedAt: "2025-04-15T16:45:00Z",
    status: "pending",
    votes: { up: 3, down: 0 },
  },
  {
    id: 3,
    productName: "IKEA Mesa LACK",
    priceArgentina: 45000,
    priceArgentinaCurrency: "ARS",
    priceUSA: 25,
    category: "home",
    sourceUrl: "https://ikea.com.ar/mesa-lack",
    contributorName: "HomeDecor",
    submittedAt: "2025-04-14T12:20:00Z",
    status: "pending",
    votes: { up: 7, down: 2 },
  },
]

// Mock data for summary KPIs
export const summaryKpis: SummaryKpiType[] = [
  {
    title: "Inflación percibida mensual",
    value: "12.8%",
    description: "Basada en variación de productos analizados",
    icon: "trending",
  },
  {
    title: "Cotización Dólar Blue",
    value: "$1,250",
    description: "+5.2% vs mes anterior",
    icon: "dollar",
  },
  {
    title: "Brecha cambiaria",
    value: "7.8%",
    description: "Diferencia entre oficial y blue",
    icon: "percentage",
  },
  {
    title: "Comparativa de ingresos",
    value: "10x",
    description: "Sueldo EE.UU. vs Argentina en USD",
    icon: "briefcase",
  },
]
